### ISSUE TITLE
Provide a way to exectute an idle call if page onload event take too long

### ISSUE THREAD

**Issue by chris-ng-scmp** [scmp/vue-idle-runner#2]
If using onload idle queue, those calls could blocked by some network request, propose set a timeout, so that onload idle call can be run after the timeout even page onload still not complete yet

**Comment by chris-ng-scmp** [comment]
#3

**Comment by chris-ng-scmp** [comment]
@jackylamscmp can you take a look of the changes? I am not sure if we need to do any update for type script? I added an option for setting timeout

**Comment by jackylamscmp** [comment]
@chris-ng-scmp I think need to update typescript for the component option: { onLoadTimeout: 10000 }, but should be able to update it later.
